services:
  postgresdb:
    image: postgres
    ports:
      - 5434:5432
    volumes:
      - ./btdt-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=btdt
